=== jimu-os/gobatis/sgo.dtd
<?xml version="1.0"?>
<!ELEMENT mapper (#PCDATA|insert|select|update|delete|for|if)*>
<!ELEMENT insert    (#PCDATA|insert|select|update|delete|for|if)*>
<!ELEMENT select    (#PCDATA|insert|select|update|delete|for|if)*>
<!ELEMENT update    (#PCDATA|insert|select|update|delete|for|if)*>
<!ELEMENT delete    (#PCDATA|insert|select|update|delete|for|if)*>
<!ELEMENT for       (#PCDATA|insert|select|update|delete|for|if)*>
<!ELEMENT if        (#PCDATA|insert|select|update|delete|for|if)*>
<!ATTLIST mapper namespace CDATA #REQUIRED>
<!ATTLIST select id CDATA #REQUIRED>
<!ATTLIST insert id CDATA #REQUIRED>
<!ATTLIST update id CDATA #REQUIRED>
<!ATTLIST delete id CDATA #REQUIRED>
<!ATTLIST for slice CDATA #REQUIRED>
<!ATTLIST for item CDATA #REQUIRED>
<!ATTLIST for open CDATA >
<!ATTLIST for close CDATA >
<!ATTLIST for column CDATA >
<!ATTLIST for separator CDATA>
<!ATTLIST if expr #PCDATA #REQUIRED>

=== jimu-os/gobatis/test.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE mapper SYSTEM "https://gitee.com/aurora-engine/sgo/blob/master/sgo.dtd">

<mapper namespace="UserMapper">
    <select id="find">
        select * from student where sss={name}
        <if expr="{arr}!=nil and {len(arr)}>0">
            and
            <for slice="{arr}" item="obj" column="id" open="("  separator="," close=")" >
                {obj}
            </for>
        </if>

        <if expr="{name}=='aaa'" >
          and abc = {name}
            <if expr="1==1">
                and 1={name}
                <if expr="1==1">
                    or 1!={name}
                </if>
            </if>
           or cba={name}
        </if>
        or  name = {name} and 1=1
    </select>

    <select id="FindUser">
        select user_age from comm_user where user_id={id}
    </select>

    <select id="UserSelect">
        select * from comm_user where user_id={id}
    </select>

</mapper>
